name: Publish release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Get current tag
        id: get_tag
        run: echo tag="$(git tag --points-at `git rev-parse HEAD`)" >> $GITHUB_OUTPUT
      - name: Publish release
        if: ${{ endsWith(github.ref, 'heads/main') && steps.get_tag.outputs.tag != false}}
        run: echo "Tagged commit on main branch, publish release!"
      - name: Publish canary release
        env:
          GITHUB_VAR: ${{ toJson(github) }}
        if: ${{ endsWith(github.ref, 'heads/main') && steps.get_tag.outputs.tag == false }}
        run: echo "Untagged commit on main branch, publish canary release!"
