name: Publish release
on:
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish release
        env:
          GITHUB_VAR: ${{ toJson(github) }}
        run: echo "$GITHUB_VAR"
