name: Publish release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      run_rest_jobs: ${{ steps.get_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Get current tag
        id: get_tag
        run: echo tag="$(git tag --points-at `git rev-parse HEAD`)" >> $GITHUB_OUTPUT
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          if [[ ${{ endsWith(github.ref, 'heads/main') && steps.get_tag.outputs.tag == false}} ]]; then
            echo "branch=development" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          fi
      - name: Publish release
        if: ${{ endsWith(github.ref, 'heads/main') && steps.get_tag.outputs.tag != false}}
        run: |
          echo "Tagged commit on main branch, publish release!"
          echo "Tag: ${{ steps.get_tag.outputs.tag }}"
          echo "Branch: ${{ steps.extract_branch.outputs.branch }}"
      - name: Publish canary release
        env:
          GITHUB_VAR: ${{ toJson(github) }}
        if: ${{ endsWith(github.ref, 'heads/main') && steps.get_tag.outputs.tag == false }}
        run: |
          echo "Untagged commit on main branch, publish canary release!"
          echo "Tag: ${{ steps.get_tag.outputs.tag }}"
          echo "Branch: ${{ steps.extract_branch.outputs.branch }}"
  needs-release:
    if: ${{ needs.release.outputs.run_rest_jobs }}
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: do something
        id: get_tag
        run: echo "does it run?"